version: '3.7'
services:
  nginx:
    build:  ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
      - mariadb
    ports:
      - '443:443'
    env_file: .env
    networks:
      - inception-net
    volumes:
      - wordpress-volume:/var/www/wordpress
    
  wordpress:
    build:  ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file: .env
    networks:
      - inception-net
    volumes:
      - wordpress-volume:/var/www/wordpress
  
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    env_file: .env
    networks:
      - inception-net
    volumes:
      - mariadb-volume:/var/lib/mysql
    
networks:
  inception-net:
    driver: bridge

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/mariadb-volume
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/wordpress-volume
      o: bind
